name: Lint

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  golangci:
    name: Golangci-Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: -E goimports -E gocritic -E misspell -E revive